### ISSUE TITLE
Liquid Exception: undefined method `gsub!' for nil:NilClass

### ISSUE THREAD

**Issue by louis-etne** [kogakure/jekyll-plugin-abbr#1]
Hello, 
When I do

``` markdown
{{BIA | abbr}}
```

I have the error 

```
Liquid Exception: undefined method `gsub!' for nil:NilClass in [...]
jekyll 2.5.3 | Error:  undefined method `gsub!' for nil:NilClass
```

Why? Thanks for your answer!

**Comment by kogakure** [comment]
Missing context of your problem. BIA is most likely nil. What is BIA? String, Hash? You know how to use a Liquid filter?

**Comment by louis-etne** [comment]
Mmm BIA is a string, it's in a markdown text no? No sorry, I don't know how to use them, I'm still learning

**Comment by kogakure** [comment]
If you want to use BIA as a word (String), you need to wrap it in quotes ("BIA"). But this filter is indented to be used on the whole content variable: {{ content | abbr }}. It will search for every word and replace it in the text. 

You can learn more about Filters and how to create your own here:
https://github.com/Shopify/liquid/wiki/Liquid-for-Designers
https://github.com/Shopify/liquid/wiki/Liquid-for-Programmers
